[workspace]

members = [
    "libs/megahx8",
    "game", "rom", "libs/convert", "libs/resources",
]

resolver = "2"


[profile.release]
lto = "fat"
panic = "abort"

[profile.dev]
lto = "fat"
panic = "abort"
